title           : Articles
description     : My Personal Stack Problems
author          : redskelt
github          : https://github.com/redskelt
about           : 기억해둬라. 독재자란 출현시킨 쪽에 더 큰 책임이 있다는 것을. 적극적으로 지지하지 않았다고 해도 말없이 지켜보고 있었다면 그 죄는 똑같다.
disqus_shortname: redskelt
google_analytics: UA-XXXXXXXX-Y
avatar_url      : /static/img/avatar.jpg

#출처정보
origin_author   : Copyright (c) 2016 Agus Makmun
origin_title    : My Stack Problems - Jekyll Theme
origin_source   : https://github.com/agusmakmun/agusmakmun.github.io
origin_license  : The MIT License (MIT)

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/redskelt"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Articles by category
      url : /category/all
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 5
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
