title           : redskelt's Blog
description     : My Personal Articles
author          : redskelt
github          : https://github.com/redskelt
about           : 당신들은 안 그럴 거라고 장담하지 마. 서는 데가 바뀌면 풍경도 달라지는 거야. -송곳-
disqus_shortname: redskelt
google_analytics: UA-98467202-1
avatar_url      : /static/img/avatar.jpg

#출처정보
origin_author   : Copyright &copy; 2016 Agus Makmun
origin_title    : My Stack Problems - Jekyll Theme
origin_source   : https://github.com/agusmakmun/agusmakmun.github.io
origin_license  : The MIT License (MIT)

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "https://twitter.com/agusmakmun6"
    # - icon: fa-linkedin
    #   link: "https://www.linkedin.com/in/summonagus"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/redskelt"

share:
  twitter_username: redskelt
  fb_appid:

urls:
    - text: Articles by category
      url : /category/Life
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://redskelt.github.io"
baseurl: ""
paginate: 20
per_page: 5
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

theme: jekyll-theme-cayman